
package Proyecto;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;

public class Consulta_clientes extends javax.swing.JDialog {
java.awt.Frame principal; 

String clave = "1999";

    public Consulta_clientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
          principal=parent;
          String s="select * from registro_cliente";
    
        DefaultTableModel df=new DefaultTableModel();
      
       df.addColumn("Cedula");
       df.addColumn("Nombre");
       df.addColumn("Edad");
       df.addColumn("Sexo");
       df.addColumn("Direccion");
       df.addColumn("Contacto");
  try {
       
       Class.forName("org.postgresql.Driver");
       Connection c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", clave);
        System.out.println("Database connected");
         PreparedStatement p = c.prepareStatement(s);
         ResultSet r=p.executeQuery();
         
         while(r.next())
         {
String registro[]={r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)};   
 df.addRow(registro);
                     
         }
    } catch (ClassNotFoundException e) {
        System.out.println("clase no encontrada");
        e.printStackTrace();
    }
     catch (SQLException e) {
        System.out.println("Database Access Error.");
        e.printStackTrace();
    }
        tabla_datos.setModel(df);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos = new javax.swing.JTable();
        Btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de clientes");

        tabla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_datos);

        Btn_modificar.setText("Modificar");
        Btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(Btn_modificar)
                        .addGap(96, 96, 96)
                        .addComponent(btn_eliminar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_modificar)
                    .addComponent(btn_eliminar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_modificarActionPerformed

        int indice=tabla_datos.getSelectedRow();

        String cedula=(String)tabla_datos.getValueAt(indice, 0);
        String nombre=(String)tabla_datos.getValueAt(indice, 1);
        String edad=(String)tabla_datos.getValueAt(indice, 2);
        String sexo=(String)tabla_datos.getValueAt(indice, 3);
        String direccion=(String)tabla_datos.getValueAt(indice, 4);
        String contacto=(String)tabla_datos.getValueAt(indice, 5);

        DatosClientes d=new DatosClientes(cedula,nombre,edad,sexo,direccion,contacto);

        Registro_cliente rc=new Registro_cliente(principal,true,d);
        rc.show();

        hide();

        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        // TODO add your handling code here:

        int indice=tabla_datos.getSelectedRow();

        String cedula=(String)tabla_datos.getValueAt(indice, 0);

        int n = JOptionPane.showConfirmDialog(
            this, "Esta seguro que desea eliminar?",
            "confirmación",
            JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {

            String s="delete from registro_cliente where cedula='"+cedula+"'";

            try {

                Class.forName("org.postgresql.Driver");
                Connection c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", clave);

                System.out.println("Database connected");

                PreparedStatement p = c.prepareStatement(s);
                p.executeUpdate();

            } catch (ClassNotFoundException e) {
                System.out.println("clase no encontrada");
                e.printStackTrace();
            }
            catch (SQLException e) {
                System.out.println("Database Access Error.");
                e.printStackTrace();

                JOptionPane.showMessageDialog(this,"no se puede eliminar: "+ e.toString());

            }

            hide();
        }

    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Consulta_clientes dialog = new Consulta_clientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_datos;
    // End of variables declaration//GEN-END:variables
}
